version: 1
datastore:
  user: user
  password: password
  hostname: mysql-kafka.westus3.cloudapp.azure.com
  port: 3306
  db: events
events:
  hostname: mysql-kafka.westus3.cloudapp.azure.com
  port: 9092
  topic: events
kafka:
  retries: 20
  wait: 20
event_log:
  topic: event_log

