version: 1
print_success:
  url: http://localhost:8090/print_success
failed_print:
  url: http://localhost:8090/failed_print
events:
  hostname: mysql-kafka.westus3.cloudapp.azure.com
  port: 9092
  topic: events
kafka:
  retries: 20
  wait: 20
event_log:
  topic: event_log

