openapi: 3.0.0
servers: []
info:
  version: "1.0.0"
  title: 3d Printer Filament Tracker
  description: For use in 3d print farms to automatically track number of spools, their colour, and the remaining quantity per spool. It will also automatically order new filament or it can be manually ordered.
tags: 
- name: spools
  description: Options for updating spools success and failures
paths:
  /print_success:
    # post:
    #   tags:
    #     - success
    #   summary: Reports that print was success and length of filament used on a specific spool
    #   description: Updates the spools amount remaining. If spool is used up also update the number of spools remaining for that colour.
    #   operationId: app.print_success
    #   responses:
    #     '200':
    #       description: successfully updated
    #     '400':
    #       description: 'invalid input, invalid object'
    #   requestBody:
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/usedSpool'
    #       description: updated spools
    get:
      tags:
        - success
      summary: Gets the status and length of filament used
      description: Get the spools amount remaining
      operationId: app.get_print_success
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of returns
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limits the number of returns
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of print successes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/usedSpool'
        '400':
          description: Invalid requestBody
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /failed_print:  
    # post:
    #   tags:
    #     - failed
    #   operationId: app.failed_print
    #   responses:
    #     '200':
    #       description: updated failure
    #     '400':
    #       description: 'invalid input, invalid object'
    #   requestBody:
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/printFailure'
    #       description: updated failure
    get:
      tags:
        - failed
      summary: Gets the failure and mm wasted
      description: Gets the failure and mm wasted
      operationId: app.get_failed_print
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of returns
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limits the number of returns
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of failed prints
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/printFailure'
        '400':
          description: Invalid requestBody
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    usedSpool:
      required:
      - spool_id
      - printer_id
      - mm_used
      - colour
      - trace_id
      properties:
        spool_id:
          type: string
          format: uuid
          example: 8528cb3f-3da8-4764-aca8-8c22a3da12aa
        printer_id:
          type: string
          example: P1S1903
        mm_used:
          type: integer
          example: 50
        colour:
          type: string
          example: red
        trace_id:
          type: string
          format: uuid
          example: 8528cb3f-3da8-4764-aca8-8c22a3da12aa
      type: object
    printFailure:
      required:
      - spool_id
      - printer_id
      - mm_wasted
      - timestamp
      - trace_id
      properties:
        spool_id:
          type: string
          format: uuid
          example: 8528cb3f-3da8-4764-aca8-8c22a3da12aa
        printer_id:
          type: string
          example: P1S1903
        mm_wasted:
          type: integer
          example: 9954821
        timestamp:
          type: string
          format: date-time
          example: '2023-01-08T10:44:23.001Z'
        trace_id:
          type: string
          format: uuid
          example: 8528cb3f-3da8-4764-aca8-8c22a3da12aa
      type: object