version: 1
datastore:
  filename: /data/stats.sqlite
scheduler:
  period_sec: 5
eventstore:
  url: http://localhost:8090
event_log:
  topic: event_log
events:
  hostname: mysql-kafka.westus3.cloudapp.azure.com
  port: 9092
  topic: events
kafka:
  retries: 20
  wait: 20
