openapi: 3.0.0
info:
  version: "1.0.0"
  title: event logs api
  description: Keep track of event log
paths:
  /event_stats:
    get:
      summary: Gets stats of event log
      description: From db
      operationId: app.get_event_stats
      responses:
        '200':
          description: Successfully returned data
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/eventStats'
        '404':
          description: No data in db
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    eventStats:
      required:
        - one
        - two
        - three
        - four
      type: object
      properties:
        one:
          type: integer
          example: 10
        two:
          type: integer
          example: 20
        three:
          type: integer
          example: 30
        four:
          type: integer
          example: 40